spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/je_pasolodyankin
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    consumer:
      group-id: inventory-group

kafka:
  bootstrap-servers: localhost:9092



server:
  port: 8082